---
env:
  vars:
    zapScanUrl: "${ZAP_SCAN_URL}"
  contexts:
  - name: "Default Context"
    urls:
      - "${zapScanUrl}"
    # includePaths:
    #   - "${zapScanUrl}"
    #   - "${zapScanUrl}/*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters:
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 20
    inScopeOnly: true
  name: "spiderAjax"
  type: "spiderAjax"
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- name: "sarif-report"
  type: "report"
  parameters:
    template: "sarif-json"
    reportTitle: "ZAP Scanning Report"
    reportDescription: "Scan report in SARIF format"
    reportDir: "/zap/wrk/"
    reportFile: "sarif-report.json"
